export const siteConfig = {
  name: "College Guide",
  description:
    "Official Tamil Nadu College Discovery, Cutoff Predictor, Academic Exploration and Admission Guidance Platform. Discover verified engineering, medical, arts, law, and agricultural colleges across all 38 districts of Tamil Nadu.",
  url: "https://collegesguide.in",
  email: "support@collegesguide.in",
  ogImage: "/logo.jpg",
  state: "Tamil Nadu",
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "919629653312",
  instagramUrl: "https://www.instagram.com/college_guide_tamil?igsi=MXg3Y2l1ajhoNGU2Yw==",
  phoneDisplay: "+91 96296 53312",
  whatsappDefaultMessage:
    process.env.NEXT_PUBLIC_WHATSAPP_DEFAULT_MESSAGE ||
    "Hi College Guide Team, I need admission guidance and cutoff assistance for colleges in Tamil Nadu.",
  mainNav: [
    { title: "Colleges", href: "/colleges" },
    { title: "TNEA Predictor", href: "/college-predictor" },
    { title: "Compare", href: "/compare" },
    { title: "Courses", href: "/courses" },
    { title: "Universities", href: "/universities" },
    { title: "Exams", href: "/exams" },
    { title: "Course Finder", href: "/course-finder" },
    { title: "Admission Help", href: "/guidance" },
  ],
  tamilNaduDistricts: [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kancheepuram",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  popularStreams: [
    { name: "Engineering & Tech", slug: "engineering", code: "BE_BTECH", icon: "Cpu" },
    { name: "Medical & Dental", slug: "medical", code: "MBBS_BDS", icon: "Activity" },
    { name: "Arts & Science", slug: "arts-science", code: "BSC_BCOM_BA", icon: "BookOpen" },
    { name: "Management & MBA", slug: "management", code: "MBA_BBA", icon: "Briefcase" },
    { name: "Law", slug: "law", code: "LLB", icon: "Scale" },
    { name: "Nursing & Allied Health", slug: "nursing", code: "BSC_NURSING", icon: "HeartPulse" },
    { name: "Agriculture", slug: "agriculture", code: "BSC_AGRI", icon: "Sprout" },
    { name: "Architecture", slug: "architecture", code: "BARCH", icon: "Building" },
  ],
};
